networks:
  app-network:
    driver: bridge

services:
  api-cms:
    build: ./api-cms
    container_name: api-cms
    networks:
      - app-network
    ports:
      - "${API_CMS_PORT}:${API_CMS_PORT}"
    environment:
      - HOSTNAME=${HOSTNAME}
      - API_CMS_PORT=${API_CMS_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_USERNAME=${MINIO_USERNAME}
      - MINIO_PASSWORD=${MINIO_PASSWORD}
      - KAFKA_PORT=${KAFKA_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - JAVA_OPTS=-Xms256m -Xmx512m
    restart: always

  web-cms:
    build: ./web-cms
    container_name: web-cms
    networks:
      - app-network
    ports:
      - "${WEB_CMS_PORT}:${WEB_CMS_PORT}"
    environment:
      - WEB_CMS_PORT=${WEB_CMS_PORT}
      - API_CMS_PORT=${API_CMS_PORT}
      - API_CMS_HOSTNAME=${API_CMS_HOSTNAME}
      - JAVA_OPTS=-Xms256m -Xmx512m
    restart: always

  api-business:
    build: ./api-business
    container_name: api-business
    networks:
      - app-network
    ports:
      - "${API_BUSINESS_PORT}:${API_BUSINESS_PORT}"
    environment:
      - HOSTNAME=${HOSTNAME}
      - API_BUSINESS_PORT=${API_BUSINESS_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_USERNAME=${MINIO_USERNAME}
      - MINIO_PASSWORD=${MINIO_PASSWORD}
      - KAFKA_PORT=${KAFKA_PORT}
      - JAVA_OPTS=-Xms256m -Xmx512m
    restart: always

  web-business:
    build: ./web-business
    container_name: web-business
    networks:
      - app-network
    ports:
      - "${WEB_BUSINESS_PORT}:${WEB_BUSINESS_PORT}"
    environment:
      - WEB_BUSINESS_PORT=${WEB_BUSINESS_PORT}
      - API_BUSINESS_PORT=${API_BUSINESS_PORT} 
      - API_BUSINESS_HOSTNAME=${API_BUSINESS_HOSTNAME}
      - JAVA_OPTS=-Xms256m -Xmx512m
    restart: always