spring.application.name=web-business
server.port=9100

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

spring.main.web-application-type=servlet