server:
    port: ${API_CMS_PORT:8000}
    servlet:
        context-path: /api-cms

spring:
    application:
        name: api-cms
    servlet:
        multipart:
            enabled: true
            max-file-size: 10MB
            max-request-size: 50MB
    devtools:
      restart:
          enabled: false
    kafka:
        bootstrap-servers: ${HOSTNAME:localhost}:${KAFKA_PORT:29092}
        listener:
            ack-mode: record
            concurrency: 3
            retry:
                max-attempts: 3
                initial-interval: 1000
                multiplier: 2.0
                max-interval: 10000
        consumer:
            group-id: my-group
            auto-offset-reset: earliest
            enable-auto-commit: false
            max-poll-records: 1

            key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
            properties:
                spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
                spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
                spring.json.ignore.unknown: true
                spring.json.use.type.headers: true
                spring.json.trusted.packages: "*"
        producer:
            acks: 1
            retries: 3
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            properties:
                spring.json.add.type.headers: true

    datasource:
        url: jdbc:postgresql://${HOSTNAME:localhost}:${DB_PORT:5432}/cms
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
        hikari:
            connection-timeout: 3000
            idle-timeout: 6000
            max-lifetime: 18000
            maximum-pool-size: 3
            validation-timeout: 5000
            minimum-idle: 1

    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

    data:
        redis:
            host: ${HOSTNAME:localhost}
            port: ${REDIS_PORT:6379}

    cache:
        type: redis

    mail:
        host: smtp.gmail.com
        port: 587
        username: dreamwalkers04@gmail.com
        password: ouhtwptcmxgbgazr
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                    connectiontimeout: 5000
                    timeout: 3000
                    writetimeout: 5000


springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        csrf:
            enabled: false
        enabled: true

minio:
    url: http://${HOSTNAME:localhost}:${MINIO_PORT:9000}
    access-key: ${MINIO_USERNAME}
    secret-key: ${MINIO_PASSWORD}
    bucket: tts

custom:
    security:
        whiteList: /v1/api/auth/**,/v3/api-docs,/v3/api-docs/**,/swagger-ui/**,/swagger-resources/**,/sw/**

sso:
    secret: ${SECRET_KEY:secrettestabcdefghijklmnopqrstuvwxyz}
    expiration:
        token: 10000
        reset_token: 36
        change_password_token: 5
