server:
    port: 8000
    servlet:
        context-path: /api-cms

spring:
    application:
        name: api-cms
    servlet:
        multipart:
            enabled: true
            max-file-size: 10MB
            max-request-size: 50MB
    devtools:
      restart:
          enabled: false
    kafka:
        bootstrap-servers: vvbach-linux:29092
        listener:
            ack-mode: record
            concurrency: 3
            retry:
                max-attempts: 3
                initial-interval: 1000
                multiplier: 2.0
                max-interval: 10000
        consumer:
            group-id: my-group
            auto-offset-reset: earliest
            enable-auto-commit: false
            max-poll-records: 1

            # Bắt buộc dùng ErrorHandlingDeserializer để bắt Serialization/Deserialization lỗi
            key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
            properties:
                spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
                spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
                spring.json.ignore.unknown: true
                spring.json.use.type.headers: true
                spring.json.trusted.packages: "*"
        producer:
            acks: 1
            retries: 3
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            properties:
                # Giữ nguyên mặc định: thêm type headers để consumer nhận diện lớp
                spring.json.add.type.headers: true
    mail:
        host: smtp.gmail.com
        port: 587
        username: dreamwalkers04@gmail.com
        password: ouhtwptcmxgbgazr
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                    connectiontimeout: 5000
                    timeout: 3000
                    writetimeout: 5000

    datasource:
        url: jdbc:postgresql://vvbach-linux:5432/cms
        username: admin
        password: admin123
        driver-class-name: org.postgresql.Driver
        hikari:
            connection-timeout: 3000
            idle-timeout: 6000
            max-lifetime: 18000
            maximum-pool-size: 3
            validation-timeout: 5000
            minimum-idle: 1

    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

    data:
        redis:
            host: vvbach-linux
            port: 6379

    cache:
        type: redis


springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        csrf:
            enabled: false
        enabled: true

minio:
    url: http://vvbach-linux:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket: tts

custom:
    security:
        whiteList: /v1/api/auth/**,/v3/api-docs,/v3/api-docs/**,/swagger-ui/**,/swagger-resources/**,/sw/**

sso:
    secret: fsdfnr5235ydflo121232#34kj2234235432549843ksdfguysfsdsfsdfgsdgsdgsdgsdgsdgwerfsdgr
    expiration:
        token: 10000
        reset_token: 36
        change_password_token: 5
